"""empty message

Revision ID: 21ee68959c41
Revises: 8ee9fb4f770e
Create Date: 2025-05-12 00:28:00.189402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ee68959c41'
down_revision = '8ee9fb4f770e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Books', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
