"""empty message

Revision ID: dc8094c5bbc4
Revises: 21ee68959c41
Create Date: 2025-05-12 22:50:28.000420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8094c5bbc4'
down_revision = '21ee68959c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
